version: '3'

networks:
    web:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.23.0.0/16
    app: ~

services:
    nginx:
        container_name: nginx
        build:
            context: server
        ports:
            - 8080:80
        volumes:
            - ../:/var/www/project
        networks:
            web:
                ipv4_address: 172.23.0.10
            app: ~

    php:
        container_name: php
        build:
            context: php/fpm
        ports:
            - 9000:9000
        volumes:
            - ../:/var/www/project
        networks:
            web:
                ipv4_address: 172.23.0.11
            app: ~

    cli:
        container_name: php_cli
        build:
            context: php/cli
        depends_on:
            - php
        volumes:
            - ../:/var/www/project
            - ~/.bash_history:/root/.bash_history
        environment:
             - "TERM=xterm-color"
             - "COMPOSER_ALLOW_SUPERUSER=1"
        networks:
            app: ~